# Generated by Django 4.0.4 on 2022-05-24 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('carbon_emissions_reduced', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
