# Generated by Django 4.0.4 on 2022-05-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reduced_carbon_savings',
            new_name='reduced_carbon_emission',
        ),
    ]
