# Generated by Django 4.0.4 on 2022-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_reduced_carbon_savings_user_reduced_carbon_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('BRIS', 'Bristol'), ('POR', 'Portsmouth'), ('MANCH', 'Manchester'), ('CAMB', 'Cambridge'), ('NEW', 'Newcastle'), ('HULL', 'Hull'), ('SAMP', 'Southampton'), ('LIV', 'Liverpool'), ('WINCH', 'Winchester'), ('LOND', 'London')], max_length=50, null=True),
        ),
    ]
