# Generated by Django 4.0.4 on 2022-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('CAMB', 'Cambridge'), ('NEW', 'Newcastle'), ('LIV', 'Liverpool'), ('MANCH', 'Manchester'), ('SAMP', 'Southampton'), ('WINCH', 'Winchester'), ('POR', 'Portsmouth'), ('HULL', 'Hull'), ('LOND', 'London'), ('BRIS', 'Bristol')], default='LOND', max_length=50, null=True),
        ),
    ]
