# Generated by Django 4.0.4 on 2022-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('LOND', 'London'), ('BRIS', 'Bristol'), ('NEW', 'Newcastle'), ('LIV', 'Liverpool'), ('CAMB', 'Cambridge'), ('HULL', 'Hull'), ('MANCH', 'Manchester'), ('POR', 'Portsmouth'), ('SAMP', 'Southampton'), ('WINCH', 'Winchester')], default='LOND', max_length=50, null=True),
        ),
    ]
