# Generated by Django 4.0.4 on 2022-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('MANCH', 'Manchester'), ('LOND', 'London'), ('WINCH', 'Winchester'), ('LIV', 'Liverpool'), ('CAMB', 'Cambridge'), ('HULL', 'Hull'), ('NEW', 'Newcastle'), ('POR', 'Portsmouth'), ('BRIS', 'Bristol'), ('SAMP', 'Southampton')], default='LOND', max_length=50, null=True),
        ),
    ]
