# Generated by Django 4.0.4 on 2022-05-29 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('test', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=355)),
                ('short_title', models.CharField(max_length=200, null=True)),
                ('publish_date', models.DateTimeField()),
                ('body', tinymce.models.HTMLField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='photos/blogs/%Y/%m/%d/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos/blogs/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/blogs/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/blogs/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
