# Generated by Django 4.0.4 on 2022-05-29 19:40

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(default=articles.models.generate_blog_post_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/articles/%Y/%m/%d/'),
        ),
    ]
