# Generated by Django 4.0.4 on 2022-05-30 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_alter_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/articles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/articles/%Y/%m/%d/'),
        ),
    ]
