# Generated by Django 4.0.4 on 2022-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/blogs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/blogs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/blogs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/blogs/%Y/%m/%d/'),
        ),
    ]
