# Generated by Django 4.0.4 on 2022-05-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color_tag', models.CharField(default='#000000', max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('item_condition', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hero_image', models.ImageField(upload_to='photos/items/%Y/%m/%d/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='photos/items/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/items/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/items/%Y/%m/%d/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='photos/items/%Y/%m/%d/')),
                ('is_public', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('door_number', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
