# Generated by Django 4.0.4 on 2022-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_address_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hero_image',
            field=models.ImageField(upload_to='share/photos/items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='share/photos/items/%Y/%m/%d/'),
        ),
    ]
