# Generated by Django 4.0.4 on 2022-05-21 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_rename_state_item_item_state_item_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='door_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
